// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutletStatusPortal.Models;

#nullable disable

namespace OutletStatusPortal.Migrations
{
    [DbContext(typeof(Outletdbcontext))]
    partial class OutletdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OutletStatusPortal.Models.Arise_Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutletSl")
                        .HasColumnType("int");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sl")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OutletSl");

                    b.ToTable("Arise_Problems");
                });

            modelBuilder.Entity("OutletStatusPortal.Models.DeviceSetupStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutletSl")
                        .HasColumnType("int");

                    b.Property<int>("Sl")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OutletSl");

                    b.ToTable("DeviceSetupStatuses");
                });

            modelBuilder.Entity("OutletStatusPortal.Models.NewOutletInfo", b =>
                {
                    b.Property<int>("Sl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sl"), 1L, 1);

                    b.Property<string>("AssignPersons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouriarStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPSLive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeITSetup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletITSetup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sl");

                    b.ToTable("NewOutletInfos");
                });

            modelBuilder.Entity("OutletStatusPortal.Models.Users", b =>
                {
                    b.Property<string>("StafId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StafId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            StafId = "l53335",
                            Date = new DateTime(2025, 7, 7, 16, 4, 5, 297, DateTimeKind.Local).AddTicks(1352),
                            Name = "Jaber Hosen",
                            PassWord = "1234",
                            Phone = "01700000001",
                            Role = "Admin"
                        },
                        new
                        {
                            StafId = "l54445",
                            Date = new DateTime(2025, 7, 7, 16, 4, 5, 297, DateTimeKind.Local).AddTicks(1355),
                            Name = "Sadia Akter",
                            PassWord = "jaber hosen",
                            Phone = "01700000002",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("OutletStatusPortal.Models.Arise_Problem", b =>
                {
                    b.HasOne("OutletStatusPortal.Models.NewOutletInfo", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletSl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outlet");
                });

            modelBuilder.Entity("OutletStatusPortal.Models.DeviceSetupStatus", b =>
                {
                    b.HasOne("OutletStatusPortal.Models.NewOutletInfo", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletSl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outlet");
                });
#pragma warning restore 612, 618
        }
    }
}
